version: '3'

services:
  billplz_db:
    image: postgres:11.2-alpine
    env_file:
      - ../.env
    ports:
      - 5400:5432

  billplz_app:
    image: registry.gitlab.com/ahmadsyafiq93/billplz-poc
    command: /start
    env_file:
      - ../.env
    depends_on:
      - billplz_db
    ports:
      - 80:80